DROP DATABASE IF EXISTS astabank;

DROP USER IF EXISTS `asta_admin`@`%`;
DROP USER IF EXISTS `asta_user`@`%`;

CREATE DATABASE IF NOT EXISTS astabank CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS `asta_admin`@`%` IDENTIFIED WITH mysql_native_password BY 'asta-db-password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `astabank`.* TO `asta_admin`@`%`;

CREATE USER IF NOT EXISTS `asta_user`@`%` IDENTIFIED WITH mysql_native_password BY 'asta-db-password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `astabank`.* TO `asta_user`@`%`;

FLUSH PRIVILEGES;